--
-- PostgreSQL database dump
--

-- Dumped from database version 12.22 (Ubuntu 12.22-0ubuntu0.20.04.4)
-- Dumped by pg_dump version 12.22 (Ubuntu 12.22-0ubuntu0.20.04.4)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: People; Type: TABLE; Schema: public; Owner: tim
--

CREATE TABLE public."People" (
    id integer NOT NULL,
    name character varying,
    catchphrase character varying
);


ALTER TABLE public."People" OWNER TO tim;

--
-- Name: People_id_seq; Type: SEQUENCE; Schema: public; Owner: tim
--

CREATE SEQUENCE public."People_id_seq"
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public."People_id_seq" OWNER TO tim;

--
-- Name: People_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: tim
--

ALTER SEQUENCE public."People_id_seq" OWNED BY public."People".id;


--
-- Name: actor; Type: TABLE; Schema: public; Owner: tim
--

CREATE TABLE public.actor (
    id integer NOT NULL,
    name character varying NOT NULL,
    age integer NOT NULL,
    gender character varying NOT NULL
);


ALTER TABLE public.actor OWNER TO tim;

--
-- Name: actor_id_seq; Type: SEQUENCE; Schema: public; Owner: tim
--

CREATE SEQUENCE public.actor_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.actor_id_seq OWNER TO tim;

--
-- Name: actor_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: tim
--

ALTER SEQUENCE public.actor_id_seq OWNED BY public.actor.id;


--
-- Name: link_movie_actor; Type: TABLE; Schema: public; Owner: tim
--

CREATE TABLE public.link_movie_actor (
    actor_id integer NOT NULL,
    movie_id integer NOT NULL
);


ALTER TABLE public.link_movie_actor OWNER TO tim;

--
-- Name: movie; Type: TABLE; Schema: public; Owner: tim
--

CREATE TABLE public.movie (
    id integer NOT NULL,
    title character varying NOT NULL,
    release_date date NOT NULL
);


ALTER TABLE public.movie OWNER TO tim;

--
-- Name: movie_id_seq; Type: SEQUENCE; Schema: public; Owner: tim
--

CREATE SEQUENCE public.movie_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.movie_id_seq OWNER TO tim;

--
-- Name: movie_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: tim
--

ALTER SEQUENCE public.movie_id_seq OWNED BY public.movie.id;


--
-- Name: People id; Type: DEFAULT; Schema: public; Owner: tim
--

ALTER TABLE ONLY public."People" ALTER COLUMN id SET DEFAULT nextval('public."People_id_seq"'::regclass);


--
-- Name: actor id; Type: DEFAULT; Schema: public; Owner: tim
--

ALTER TABLE ONLY public.actor ALTER COLUMN id SET DEFAULT nextval('public.actor_id_seq'::regclass);


--
-- Name: movie id; Type: DEFAULT; Schema: public; Owner: tim
--

ALTER TABLE ONLY public.movie ALTER COLUMN id SET DEFAULT nextval('public.movie_id_seq'::regclass);


--
-- Data for Name: People; Type: TABLE DATA; Schema: public; Owner: tim
--

COPY public."People" (id, name, catchphrase) FROM stdin;
\.


--
-- Data for Name: actor; Type: TABLE DATA; Schema: public; Owner: tim
--

COPY public.actor (id, name, age, gender) FROM stdin;
1	Leonardo di Caprio	50	male
2	Kate Winslet	29	female
3	Quatsch	-1	
\.


--
-- Data for Name: link_movie_actor; Type: TABLE DATA; Schema: public; Owner: tim
--

COPY public.link_movie_actor (actor_id, movie_id) FROM stdin;
\.


--
-- Data for Name: movie; Type: TABLE DATA; Schema: public; Owner: tim
--

COPY public.movie (id, title, release_date) FROM stdin;
1	Titanic	1998-07-09
2	Titanic 2	2025-07-08
\.


--
-- Name: People_id_seq; Type: SEQUENCE SET; Schema: public; Owner: tim
--

SELECT pg_catalog.setval('public."People_id_seq"', 1, false);


--
-- Name: actor_id_seq; Type: SEQUENCE SET; Schema: public; Owner: tim
--

SELECT pg_catalog.setval('public.actor_id_seq', 3, true);


--
-- Name: movie_id_seq; Type: SEQUENCE SET; Schema: public; Owner: tim
--

SELECT pg_catalog.setval('public.movie_id_seq', 2, true);


--
-- Name: People People_pkey; Type: CONSTRAINT; Schema: public; Owner: tim
--

ALTER TABLE ONLY public."People"
    ADD CONSTRAINT "People_pkey" PRIMARY KEY (id);


--
-- Name: actor actor_name_key; Type: CONSTRAINT; Schema: public; Owner: tim
--

ALTER TABLE ONLY public.actor
    ADD CONSTRAINT actor_name_key UNIQUE (name);


--
-- Name: actor actor_pkey; Type: CONSTRAINT; Schema: public; Owner: tim
--

ALTER TABLE ONLY public.actor
    ADD CONSTRAINT actor_pkey PRIMARY KEY (id);


--
-- Name: link_movie_actor link_movie_actor_pkey; Type: CONSTRAINT; Schema: public; Owner: tim
--

ALTER TABLE ONLY public.link_movie_actor
    ADD CONSTRAINT link_movie_actor_pkey PRIMARY KEY (actor_id, movie_id);


--
-- Name: movie movie_pkey; Type: CONSTRAINT; Schema: public; Owner: tim
--

ALTER TABLE ONLY public.movie
    ADD CONSTRAINT movie_pkey PRIMARY KEY (id);


--
-- Name: movie movie_title_key; Type: CONSTRAINT; Schema: public; Owner: tim
--

ALTER TABLE ONLY public.movie
    ADD CONSTRAINT movie_title_key UNIQUE (title);


--
-- Name: link_movie_actor link_movie_actor_actor_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: tim
--

ALTER TABLE ONLY public.link_movie_actor
    ADD CONSTRAINT link_movie_actor_actor_id_fkey FOREIGN KEY (actor_id) REFERENCES public.actor(id);


--
-- Name: link_movie_actor link_movie_actor_movie_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: tim
--

ALTER TABLE ONLY public.link_movie_actor
    ADD CONSTRAINT link_movie_actor_movie_id_fkey FOREIGN KEY (movie_id) REFERENCES public.movie(id);


--
-- PostgreSQL database dump complete
--

